### ISSUE TITLE
Upgrade NodeJS to v18

### ISSUE THREAD

**Issue by guihkx** [flathub/io.github.martinrotter.rssguard#16]
We currently bundle version 16 of NodeJS/npm, which is now [end of life](https://nodejs.dev/en/about/releases/):

![image](https://github.com/flathub/io.github.martinrotter.rssguardlite/assets/626206/7ce3ec64-fa19-4197-8629-af0b661e420a)

Upgrading to v18 shouldn't be hard, but manual testing will be needed to ensure things won't break for users after the upgrade.

**Comment by martinrotter** [comment]
I see. I will try to test with npn/node 18 on windows to see if AdBlock and readability features work with it.

**Comment by martinrotter** [comment]
@guihkx Just tested nodejs 18.8 with bundled npm and it works, also updating versions of packages used by RSS Guard and those work nicely too.

You can make PR to bundle newer nodejs therefore.
