### ISSUE TITLE
Theme is not changing based on system

### ISSUE THREAD

**Issue by pm4rcin** [flathub/io.github.martinrotter.rssguard#58]
Hi, I use breeze theme and have configured `darkman` to toggle the theme with gsettings. Every application works fine but rssguard just doesn't change at all. Only the tray icon menu is changing to dark and light with the rest of the system but the whole rssguard window stays on initial theme that was set on program startup. It should pick this up via portal but maybe it's just not implemented?
I have set Breeze, icons hicolor (even though it's using breeze ones) and have set the option use skin colors to true.

**Comment by guihkx** [comment]
I could be wrong, but I think this is not implemented in RSS Guard itself, yet.

So, can you please also test with one of the [official AppImage packages](https://github.com/martinrotter/rssguard/releases/latest), or with the official repositories package (assuming your distro has it)?

If you're able to reproduce the issue with these other packages, please open an issue on the [upstream repository](https://github.com/martinrotter/rssguard/) instead.

I'll close this one now, but feel free to re-open it if you determine that this issue only affects this Flatpak package.

**Comment by pm4rcin** [comment]
You're right. Filled Feature Request here https://github.com/martinrotter/rssguard/issues/1389
