### ISSUE TITLE
Autostart feature not working

### ISSUE THREAD

**Issue by martinrotter** [flathub/io.github.martinrotter.rssguard#9]
It seems that we need to enable access to "$HOME/.config/autostart" because at this point "autostart" feature when enabled in RSS Guard settings does not work as it creates autostart desktop file in "$HOME/.var/app/io.github.martinrotter.rssguard/config/autostart" instead.

Or could it be that flatpak sandbox sets its own "XDG_CONFIG_HOME" envvar?

**Comment by guihkx** [comment]
Yup, that feature won't work unless we manually give the app permission to write on the `~/.config/autostart` directory, i.e.:
```
$ flatpak override --user --filesystem=xdg-config/autostart io.github.martinrotter.rssguard
```

I suppose we could add this information to the README of this repository.

The other option is to implement the autostart feature using DBus, which is something [I mentioned before](https://github.com/martinrotter/rssguard/discussions/825#discussioncomment-4009329).

However, there's no DBus method to check if our app is already set to autostart (as far as I know), making that checkbox in RSS Guard's settings useless. :/

**Comment by martinrotter** [comment]
Yes. Is it bad to add the permission by default?

**Comment by guihkx** [comment]
Well, if we did that the build job would simply fail, because nowadays Flathub has a manifest linter that [explicitly disallows](https://github.com/flathub/flatpak-builder-lint/blob/e863ced439bbd0716e7f12b8d27ace42a841a53f/flatpak_builder_lint/checks/finish_args.py#L67-L71) that permission by default.

We could ask Flathub maintainers to make an exception for this app, but to be honest I don't think they will do it, because it's likely they'll argue this should be done using portals (i.e. via that DBus interface I mentioned earlier), which is "more secure".

**Comment by martinrotter** [comment]
I see. So in that case, simply add to readme.

Question is to which readme? I Guess that "metainfo" XML file will be best since it is displayed in flathub store page?

**Comment by guihkx** [comment]
>Question is to which readme? I Guess that "metainfo" XML file will be best since it is displayed in flathub store page?

That might actually be a better idea, yeah.

Especially because doing that will also cover both "Regular" and "Lite" builds.

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/commit/163096a1bc2b5300a452d10a624e541625a013e3

**Comment by guihkx** [comment]
Very nice. I think we can tweak the message a bit, though.

I'd mention that command is only needed for Flatpak. You see, the `metainfo.xml` is not Flatpak-specific, so it's possible that another non-Flatpak app store also displays that message for non-Flatpak users.

Perhaps a message similar to this one would be more optimal:

>\<p\>
>Note for Flatpak users: The autostart feature can only work if you manually allow us access to the \<pre\>~/.config/autostart\</pre\> directory. You can easily do that with the following command:
>\</p\>
>\<p\>
> \<pre\>flatpak override --user --filesystem=xdg-config/autostart @APP_REVERSE_NAME@\</pre\>
>\</p\>

**Comment by martinrotter** [comment]
done
